backend/disquotes/__init__.py
# This Python file uses the following encoding: utf-8
import logging
import os

from flask import Flask
from raven.contrib.flask import Sentry

from disquotes.model.auth import discord
from disquotes.model.handlers import (before_request, commit_sql, connect_redis, connect_sql, disconnect_redis,
                                      disconnect_sql)
from disquotes.views import api, frontend

app = Flask(__name__)
app.secret_key = os.environ.get("APP_SECRET", os.environ.get("SECRET_KEY"))
app.config["SESSION_COOKIE_NAME"] = "disquotes"

# Debug
app.config["PROPAGATE_EXCEPTIONS"] = True

if "DEBUG" in os.environ:
    app.config["DEBUG"] = True

if app.debug:
    app.config["TEMPLATES_AUTO_RELOAD"] = True

app.config["SENTRY_INCLUDE_PATHS"] = ["disquotes"]
sentry = Sentry(
    app,
    dsn=app.config.get("SENTRY_DSN", None),
    logging=True,
    level=logging.ERROR,
)

# Handlers

app.before_request(connect_sql)
app.before_request(connect_redis)
app.before_request(before_request)
app.after_request(commit_sql)
app.teardown_request(disconnect_sql)
app.teardown_request(disconnect_redis)

# Routes

app.register_blueprint(frontend.blueprint)
app.register_blueprint(discord, url_prefix="/auth")
app.register_blueprint(api.blueprint, url_prefix="/api")

backend/disquotes/lib/__init__.py
# coding=utf-8

backend/disquotes/model/__init__.py
# This Python file uses the following encoding: utf-8
import datetime
import os

from sqlalchemy import BigInteger, Boolean, Column, DateTime, ForeignKey, Integer, String, Unicode, create_engine
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import relationship, scoped_session, sessionmaker, validates
from sqlalchemy.schema import Index

from disquotes.model.types import EVENT_TYPES

debug = os.environ.get('DEBUG', False)

engine = create_engine(os.environ["POSTGRES_URL"], convert_unicode=True, pool_recycle=3600)

if debug:
    engine.echo = True

sm = sessionmaker(autocommit=False,
                  autoflush=False,
                  bind=engine)

base_session = scoped_session(sm)

Base = declarative_base()
Base.query = base_session.query_property()


def now():
    return datetime.datetime.now()


class Server(Base):
    __tablename__ = "servers"
    id = Column(Integer, primary_key=True)
    server_id = Column(BigInteger, nullable=False, unique=True)

    name = Column(Unicode(100))

    meta = Column(JSONB)


class Channel(Base):
    __tablename__ = "channels"
    id = Column(Integer, primary_key=True)
    channel_id = Column(BigInteger, nullable=False, unique=True)
    server_id = Column(ForeignKey("servers.id"), nullable=False)
    name = Column(Unicode(100))
    server = relationship("Server")

    meta = Column(JSONB)


class Event(Base):
    __tablename__ = 'events'
    id = Column(Integer, primary_key=True)
    server_id = Column(ForeignKey("servers.id"), nullable=False)
    channel_id = Column(ForeignKey("channels.id"))
    posted = Column(DateTime(), nullable=False, default=now)

    type = Column(String(32), nullable=False)
    data = Column(JSONB, nullable=False)

    server = relationship("Server")
    channel = relationship("Channel")

    def to_dict(self):
        return self.data if self.data else {}

    @validates("type")
    def validate_type(self, _key, event_type):
        assert event_type in EVENT_TYPES
        return event_type


class Message(Base):
    __tablename__ = 'messages'
    id = Column(Integer, primary_key=True)

    message_id = Column(BigInteger, nullable=False, unique=True)
    server_id = Column(ForeignKey("servers.id"), nullable=False)
    channel_id = Column(ForeignKey("channels.id"), nullable=False)
    author_id = Column(BigInteger, nullable=False)
    pinned = Column(Boolean, default=False, server_default='f')
    tts = Column(Boolean, default=False, server_default='f')
    attachments = Column(JSONB, default=[])
    reactions = Column(JSONB, default=[])
    embeds = Column(JSONB, default=[])

    created = Column(DateTime)
    edited = Column(DateTime)
    message = Column(Unicode, nullable=False)

    server = relationship("Server")
    channel = relationship("Channel")

    def to_dict(self):
        return dict(
            message_id=self.message_id,
            author_id=self.author_id,
            server_id=self.server_id,
            channel_id=self.channel_id,
            pinned=self.pinned or False,
            tts=self.tts or False,
            attachments=self.attachments or [],
            reactions=self.reactions or [],
            embeds=self.embeds or [],
            created=self.created,
            edited=self.edited,
            message=message
        )

class Permission(Base):
    __tablename__ = "permissions"
    id = Column(Integer, primary_key=True)
    server_id = Column(ForeignKey("servers.id"), nullable=False)
    channel_id = Column(ForeignKey("channels.id"))
    permission = Column(String, nullable=False)


Index("permission_server", Permission.server_id)

backend/disquotes/model/auth.py
# coding=utf-8
import os
from functools import wraps

from flask import redirect, url_for
from flask_dance.consumer import OAuth2ConsumerBlueprint

from disquotes.lib.cache import redis_cache


def require_login(f):
    @wraps(f)
    def inner(*args, **kwargs):
        if not discord.session.authorized:
            return redirect(url_for("oauth-discord.login"))
        return f(*args, **kwargs)
    return inner


@redis_cache.cache_on_arguments("access_token")
def get_servers(access_token):
    return discord.session.get("users/@me/guilds").json()


def get_user_managed_servers(guilds):
    return list(
        filter(
            lambda g: (g['owner'] is True) or
            bool((int(g['permissions']) >> 3) & 1) or  # Manage Server
            bool((int(g['permissions']) >> 5) & 1),    # Administrator
            guilds
        )
    )

discord = OAuth2ConsumerBlueprint(
    "oauth-discord", __name__,
    client_id=os.environ.get("DISCORD_CLIENT_ID"),
    client_secret=os.environ.get("DISCORD_CLIENT_SECRET"),
    base_url="https://discordapp.com/api/",
    token_url="https://discordapp.com/api/oauth2/token",
    authorization_url="https://discordapp.com/api/oauth2/authorize",
    scope=["identify", "guilds"],
)

backend/disquotes/views/__init__.py
# coding=utf-8

backend/disquotes/views/frontend.py
# coding=utf-8
from flask import Blueprint, g, redirect, render_template, session, url_for
from sqlalchemy.orm.exc import NoResultFound

from disquotes.model import Event, Server
from disquotes.model.auth import get_servers, get_user_managed_servers, require_login

blueprint = Blueprint("frontend", __name__)


@blueprint.before_request
def before_app():
    if "oauth-discord_oauth_token" in session:
        g.session_token = session["oauth-discord_oauth_token"]["access_token"]
        g.servers = get_servers(g.session_token)


@blueprint.route("/")
@require_login
def front():
    user_servers = get_user_managed_servers(g.servers)
    quoted_servers = [str(x[0]) for x in g.db.query(Server.server_id).all()]

    return render_template(
        "index.html",
        user_servers=user_servers,
        quoted_servers=quoted_servers
    )


@blueprint.route("/server/<serverid>/deleted")
@require_login
def deleted_messages(serverid=None):
    if not serverid:
        return redirect(url_for("frontend.front"))

    try:
        server = g.db.query(Server).filter(Server.server_id == serverid).one()
    except NoResultFound:
        return redirect(url_for("frontend.front"))

    events = g.db.query(Event).filter(Event.server_id == server.id).order_by(Event.posted.desc()).limit(200).all()

    return render_template(
        "events.html",
        server=server,
        events=events
    )

backend/disquotes/templates/base.html
{% macro render_event(_) %}
{% set type = _.type %}
{% set event = _.data %}

<div class="event {{type}}">
{% if type == "edit" %}
<p class="edit"><span class="username">{{event.sender.display_name}}</span> has edited their message</p>
<ul>
    <li>{{event.edit.before}}</li>
    <li>{{event.edit.after}}</li>
</ul>
{% elif type == "delete" %}
<p><span class="username">{{event.sender.display_name}}</span> has deleted their message.</p>
<ul><li>{{event.message}}</li></ul>
{% elif type == "rename" %}
<p><span class="username">{{event.old}}</span> is now known as <span class="username">{{event.new}}</span></p>
{% elif type == "join" %}
<p><span class="username">{{event.name}}</span> has joined the server. </p>
{% elif type == "rename_server" %}
<p><span class="server">{{event.server.before}}</span> has been renamed to <span class="server">{{event.server.after}}</span></p>
{% elif type == "rename_channel" %}
<p><span class="channel">{{event.channel.before}}</span> has been renamed to <span class="channel">{{event.channel.after}}</span></p>
{% else %}
<h1 class="title is-1">UNKNOWN {{type}}</h1>
<pre>{{event}}</pre>
{% endif %}
</div>
{% endmacro %}
<!doctype html>
<html>
    <head>
        <meta charset="ut®f-8">
        <meta http-equiv="x-ua-compatible" content="ie=edge">
        <title>Disquotes{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link rel="stylesheet" href="/static/css/normalize.css">
        <link rel="stylesheet" href="http://yui.yahooapis.com/pure/0.6.0/pure-min.css">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">
        <link href="https://fonts.googleapis.com/css?family=Atma:300,400,500,600,700" rel="stylesheet">
        <link rel="stylesheet" href="/static/css/disquotes.css">
        <script src="//twemoji.maxcdn.com/2/twemoji.min.js?2.2"></script>
        {% block styles %} {% endblock %}
    </head>
    <body>
        <div class="pure-menu pure-menu-horizontal">
            <a href="#" class="pure-menu-heading pure-menu-link"><p id="textlogo">Quotes <3</p></a>
        </div>
        <div class="container center">
            {% block content %} {% endblock %}
        </div>

        <script src="/static/js/disquotes.js"></script>
        <script src="https://code.jquery.com/jquery-3.1.0.min.js"></script>
        {% block scripts %} {% endblock %}
    </body>
</html>

backend/disquotes/templates/events.html
{% extends "base.html" %}

{% block content %}
<div class="pure-g">
    <div class="pure-u-1">
        <h1>Events</h1>
        <ul>
        {% for event in events %}
        <li>{{render_event(event)}}</li>
        {% endfor %}
        </ul>
    </div>
</div>
{% endblock %}

backend/disquotes/templates/index.html
{% extends "base.html" %}

{% block content %}
<div class="columns">
    <div class="column">
        <h1> Servers </h1>
        {% for server in user_servers if server["id"] in quoted_servers %}
        <h2 class="server">{{server.name}}</h2>
        <ul>
            <li><a href="{{url_for("frontend.deleted_messages", serverid=server.id)}}">Deleted</a></li>
            <li><a href="{{url_for("frontend.deleted_messages", serverid=server.id)}}">Deleted</a></li>
        </ul>
        {% endfor %}
    </div>
</div>
{% endblock %}